### ISSUE TITLE
Transfer of resources and indicators to {mapme.biodiversity}

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.indicators#25]
Hi @karpfen,

I prepared branch [integration](https://github.com/mapme-initiative/mapme.indicators/tree/integration) where I tried to prep the resources, indicators, data, and tests as far as possible to integrate them into `mapme.biodiversity`. I'd guess the gold standard would be to now cherry-pick the parts that we want to integrate and leave out the rest in order to maintain the history and correct authorship. However, since we have here 80+ commits, I guess this is really labor intensive. I wanted to propose that I'll simply add the resources/indicators one by one manually to `mapme.biodiversity` but amend the commits to reference us both as authors? Would you agree to this or do you have any other suggestions?

**Comment by goergen95** [comment]
Another alternative I could imagine would be to open a PR for each resource and indicator individually.

**Comment by karpfen** [comment]
I don't have practical experience with this, but maybe squashing the 80+ commits before cherry picking would make the first approach doable.
It it's possible to maintain the history without too much extra work I'd prefer that, but I can absolutely live with any other solution as well.

**Comment by goergen95** [comment]
Hi @karpfen,
the current [changelog](https://github.com/mapme-initiative/mapme.biodiversity/blob/main/NEWS.md) is already quite extensive. I am considering a CRAN release prior to addressing this ticket (at least if, as discussed, this means also addressing reworking the engine and read of raster resources). Alternatively, we could merge now, release to CRAN, and then address outstanding issues with the engine. Any preferences?

**Comment by goergen95** [comment]
Also pinging @Jo-Schie FYI

**Comment by karpfen** [comment]
I tend towards finishing all backend stuff first and then deal with the remaining indicators from the `mapme.indicators` package, because I think these changes have more impact.
I only see one advantage when we merge the two repos first: we ensure continuous compatibility of all indicators with `mapme.biodiversity`. But I don't think this is super important, because people can just use an older version of `mapme.biodiversity` in the interim time.


But why not just put everyting in one big CRAN update?

**Comment by goergen95** [comment]
There is the concept of [release early, release often](https://en.wikipedia.org/wiki/Release_early,_release_often). We already have merged a quite substantial number of changes since release of v.0.8.0. Reworking the engine and changing the read behavior are quite intrusive changes which I feel require more thoughts into the design choices, evaluation of performance and testing.  However, I would not like to wait to release the changes we currently have (plus the new resources and indicators) until we are more confident with the changes in the backend.

**Comment by goergen95** [comment]
Linking [#240](https://github.com/mapme-initiative/mapme.biodiversity/issues/240)

**Comment by karpfen** [comment]
Does that mean you're proposing three CRAN updates?
- All current changes
- Backend changes
- `mapme.indicators` merge

**Comment by goergen95** [comment]
That is only one option. I guess my current proposition is:
 
  - merge indicators -> CRAN relase v0.9
  - backend changes -> CRAN relase v.0.10

**Comment by karpfen** [comment]
Sounds good to me! The current list of changes then also goes into v0.9, right?

**Comment by goergen95** [comment]
Right!

**Comment by goergen95** [comment]
If you agree, would you mind opening PRs then for the resources/indicators you worked on based of off the [integration](https://github.com/mapme-initiative/mapme.indicators/tree/integration) branch?
